# Generated by Django 6.0.6 on 2026-07-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Remote', 'Remote'), ('Inactive', 'Inactive'), ('Remove Employee', 'Remove Employee')], default='Active', max_length=20),
        ),
    ]
